applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/KalyanovAnton/DevOps.git
      path: lesson-5/charts/django-app
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/KalyanovAnton/DevOps.git
    username: KalyanovAnton
    password: ""

repoConfig:
  insecure: "true"
  enableLfs: "true"