apiVersion: v1
kind: Secret
metadata:
  name: infra-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/KalyanovAnton/DevOps
  password: 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