pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["99d"]
    env:
        - name: AWS_REGION
          value: "us-west-2"
    - name: git-tool
      image: alpine/git:latest
      command: ["sleep"]
      args: ["99d"]
"""
    }
  }

  environment {
    ECR_REPO    = "${env.ECR_REPOSITORY_URL ?: '963894087696.dkr.ecr.us-west-2.amazonaws.com/lesson-5-ecr'}"
    IMAGE_TAG   = "${env.BUILD_NUMBER}" 
    GITHUB_REPO = "KalyanovAnton/DevOps"
  }

stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
           
            mkdir -p /kaniko/.docker
            echo '{"credsStore": "ecr-login"}' > /kaniko/.docker/config.json
            /kaniko/executor \
              --context=dir://my_project \
              --dockerfile=my_project/Dockerfile \
              --destination=$ECR_REPO:$IMAGE_TAG \
              --cache=true
          '''
        }
      }
    }
    stage('Update Helm Values & Push') {
      steps {
        container('git-tool') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
            sh """
              # 1. Налаштовуємо Git
              git config --global user.email "jenkins@goit.local"
              git config --global user.name "Jenkins CI"

              # 2. Клонуємо репозиторій
              git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/${GITHUB_REPO}.git config-repo
              cd config-repo

              # 3. Оновлюємо тег у values.yaml
              sed -i 's/tag:.*/tag: "${IMAGE_TAG}"/g' lesson-5/charts/django-app/values.yaml || sed -i 's/tag:.*/tag: "${IMAGE_TAG}"/g' my_project/values.yaml

              # 4. Комітимо та пушимо
              git add .
              git commit -m "Update image tag to ${IMAGE_TAG} [skip ci]" || echo "No changes to commit"
              git push origin main
            """
          }
        }
      }
    }
  }
}