serviceAccount:
  create: false
  name: jenkins-sa

controller:
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi    

  image:
    repository: "jenkins/jenkins"
    tag: "2.504.1-jdk17"    



installPlugins:
  - kubernetes:latest
  - workflow-aggregator:latest
  - git:latest
  - configuration-as-code:latest
  - credentials-binding:latest
  - job-dsl:latest

JCasC:
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-token
                      username: KalyanovAnton
                      password: YOUR_GITHUB_TOKEN
                      description: GitHub PAT
      seed-job: |
        jobs:
          - script: >
              job('seed-job') {
                description('Job to generate pipeline for Django project')
                scm {
                  git {
                    remote {
                      url('https://github.com/KalyanovAnton/DevOps')
                      credentials('github-token')
                    }
                    branches('*/main')
                  }
                }
                steps {
                  dsl {
                    text('''
                      pipelineJob("goit-django-docker") {
                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url("https://github.com/KalyanovAnton/DevOps")
                                  credentials("github-token")
                                }
                                branches("*/main")
                              }
                            }
                          }
                        }
                      }
                    ''')
                  }
                }
              }